$ANSIBLE_VAULT;1.1;AES256
65656231326661333061326237656664396163636632626663353736333666326565643361343463
6130316631346131633031653537363638316634653562630a666461323437356265613062363561
32393236653332326564303364626536393164353030376332643063316165383966616432333965
6139353261623139300a326532303961346139326636623931393532343966386266326239646635
66643436353535343865303462663566313964363136316436303861663665393161353535643463
36343038393135303332666539396339326265626362303261373239633032656638653830333437
39663965333233383035633737313630623738616661633030626534306539396133336365623435
36363730663466633734646434666364363462373932336232646164613936646233313130313862
30663636343633643165373135303164336238613332613038633034656462376539393638656332
39386134643132373933316265343066303464653937313938353134336134393964376563623134
64383761643661623765646566656539336536376133373165626631643866363430393731613462
34366563343131323233393130333839633762363738333261363134623864323939383430646634
32326364653639306337633566383065626163613139656361353966373665363562346161623165
32636631663134663134633636613837313661636236633539616336313139643563326431373666
383232623562626533316633306264346239
