$ANSIBLE_VAULT;1.1;AES256
30633732643332303230633461386435313133633263643366613231393930623030303163326633
6235326430343737376536616135326336316562643038610a656332333032356132386264336638
36663962393435663663326530653934323832393834323037386432346661353064326135326337
3533396366376233630a616538366232623266343632356535343463303164333837366432383038
61663035636536316666613865633538656566383436303761333464316431333538303766613332
66316332353966396261336535316362343762366336346464333261656635373935656633626361
61353564346235363431376631646333326565363536306264636433633430643766313137663938
31656636636331633664316633653561376234366163656237616232336361326630313436636165
61363836306639366162363866353637653664633330373866373066303438323865336464353632
36383731616166616139383366613331363861363063303734666265323565373636663932333535
34623937663634616330336166393533653130346336383166336463323735366230356632623763
66323661643365653834356361643635613363393530383730393461353838633139336235333732
65346465613639366330353562346362373766333763333865363737343535636531306533306237
64346335356261363762633164633538613662353637353364626631323165616661623032326335
336130646262343764393264613834623231
