ansible_user: kirillt
ansible_ssh_private_key_file: ~/.ssh/ssh-key-1765287244855

install_docker: false
app_domain: ktarasenko.online

ssh_public_key: "{{ lookup('file', playbook_dir + '/files/kirillt.pub') }}"
