$ANSIBLE_VAULT;1.1;AES256
36373261303033613731346438336564386662386338666264643362613633313132656431343738
3134353931343734376565663330396131383861316435650a353437313539643432316336323263
30336166656536326331343664383363336564306161333837386439386662333662623832643638
6663653433313864310a616333666539663631333734313132306535646265343437343161333365
32346637353433306435303861633332386434303239333330383733666365376333356562643532
37336533316163326334633538323830633333653763323130376331626439356637643034386137
31303966306437396461363031646633313165333364346161313663623332613932386338323434
31353130343962343132616636656363366237323737313539653336326637633836343930643232
39303037666337386261623964396265643033393135363630383562366333353337323034313931
61356361656366646530383464636637366662653137313138363864346432373632333939616532
36343661313934326637646362323531633863636138663131306639623630613632663166326433
35613633666339323238616632616430356265343335313236363530383938323638386264346539
36326530336562636633663532373136343034633665353135663034333732353834396532366535
34613966666239646631646365303964386330346163363733623762313862393234396636636461
35303666663862366235373530663530363134386261613165663664363164623261383533663036
33323033383763663735393732653439633233366662336533643532643162386134613863326331
64626565363639623562346633656336643336313165333630313664656366653162623739353166
36336631633662343061623336393761623662373762646132383239376438336265313738353766
35613731656531333233663733323261356363363566633931353839316634303338366236386165
31326634656431303762643863316230343630643166363739643830656165396130646339383736
35623862393338643437376163313235646164623236383764323538373965353337623262633561
65633838386334636662386464373738643636643366656262333864373363386438666534633364
63303435366565653235623864633539396531643231353039633866373835373632663736336337
33646262346132626633323561396165366537313565353038626636636531396134656534613861
39626434353838656238383939316361356233653534363861376434336264373833653936653338
64636436376330646432613032613562646432366465356330326461306436326630393338616233
30616332663031656537363534613133356534373031333862396138636333383536663263623735
36363534656236333330633465303530356337353063623734323766316561306336663136623266
66623731343066353933346432636233393335346134313838353733623562366161336466663338
63646661373237396163613637333563313033653066626633333630343736336133336438643764
31393236306362643533616131303965663863346366623463613161303737376235353038343733
61623437326565373234663831336266323238393366386238643339393231373264323335326665
6662
