zone: ru-central1-d
ubuntu_image_id: fd8gm9cegc39t4nsm8cv
domain_zone: ktarasenko.online.
domain: ktarasenko.online
folder_id: "{{ vault_folder_id }}"
cloud_id: "{{ vault_cloud_id }}"
path_to_authorized_key: "{{ vault_path_to_authorized_key }}"
ssh_user: "{{ vault_ssh_user }}"
db_password: "{{ vault_db_password }}"
db_user: "{{ vault_db_user }}"
datadog_api_key: "{{ vault_datadog_api_key }}"
datadog_app_key: "{{ vault_datadog_app_key }}"
datadog_api_url: https://api.datadoghq.eu/
