$ANSIBLE_VAULT;1.1;AES256
31393233656430623064653834656663363536323539386238393862353930663663393864343936
6338613631323034383465306130313832666663373933660a383664316264306637343833353531
62623935313565663864613830376531646432623163373464613963376439386334303436633264
3566336263643530360a373634323362633963626366386637393862626431346230323861663237
31326331613533303939343937343839356536363862663662363565353563303066316463393439
33356232666630303239343262393335353262323833303961336663643363316265636330306662
66633433313532613963373239626364383634396564373135626638336135363032343933313739
66393538316235636635383039323439323334343237646434313463386665366262343532376462
38353437663039653065643739383330313564663662666234376439393235643163383866626139
65343031363761336162383831303837616265346330323065623532336339613665663366626138
62323463346338373062363136643339343564663835626234333962383463343662333262343431
38653939346264663865653936623935656161366335313565346531616535656362333962363962
64373065336534323138633032326162366532356339626536396336393037646239366666653132
61383163326533636165656531336639346536666637386635316430313262343866333362393765
33313235626136353236346334303365653564646438376163653236306336616266353237323539
66666135616436646263363431303333386439373062656538653933356636653930343436623237
64653562333834346562313962393037333061353363633763353265346466323732626330383837
32633532613564366432663136383264646462353066656633343665313163396336336334653066
38643132306537323838626632343637613131393235396665346636313439353533303839656532
30396135313666383936323362623932353335636434633332623630333936643364316363613966
31383261636666383734616561386362623734356532343362336336636438366433
